/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  PackedDoubleEndedQueue,
  PackedDoubleEndedQueueInterface,
} from "../../../contracts/lib/PackedDoubleEndedQueue";

const _abi = [
  {
    inputs: [],
    name: "InvalidSlot",
    type: "error",
  },
  {
    inputs: [],
    name: "QueueEmpty",
    type: "error",
  },
  {
    inputs: [],
    name: "QueueFull",
    type: "error",
  },
  {
    inputs: [],
    name: "QueueOutOfBounds",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212202b561c2c2de611bbc7f741a0acb614614c9f63ca6cf235f72db4459b81f6d69664736f6c63430008180033";

type PackedDoubleEndedQueueConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PackedDoubleEndedQueueConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PackedDoubleEndedQueue__factory extends ContractFactory {
  constructor(...args: PackedDoubleEndedQueueConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      PackedDoubleEndedQueue & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): PackedDoubleEndedQueue__factory {
    return super.connect(runner) as PackedDoubleEndedQueue__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PackedDoubleEndedQueueInterface {
    return new Interface(_abi) as PackedDoubleEndedQueueInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): PackedDoubleEndedQueue {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as PackedDoubleEndedQueue;
  }
}
