/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Auction } from "./Auction";
export type { ERC404Marketplace } from "./ERC404Marketplace";
export type { Hero404 } from "./Hero404";
export type { USDT } from "./USDT";
export type { Vault } from "./Vault";
