/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export * as lib from "./lib";
export * as token from "./token";
export { ERC404__factory } from "./ERC404__factory";
